### ISSUE TITLE
[Tips]: https://aws.amazon.com/blogs/networking-and-content-delivery/automated-vpc-prefix-list-population-for-cross-region-and-in-region-security-group-referencing/

### ISSUE THREAD

**Issue by bwhaley** [aws/eks-news#10]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**
URL: 
Title: 

**Which service(s) is this request for?**
This could be Fargate, EKS, ECR, etc.

**Tell us about what you're submitting**
What are some of the key points or benefits being suggested?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by chris-short** [comment]
Thank you!
But, this doesn't include anything about EKS or Kubernetes.
