### ISSUE TITLE
[Tips]: March 7 Meetup Talk: EKS Anywhere Deployed on VMware Complete with an API Gateway

### ISSUE THREAD

**Issue by murphye** [aws/eks-news#18]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**
URL: https://www.meetup.com/Omaha-Amazon-Web-Services-Meetup/events/283889886
Title: EKS Anywhere Deployed on VMware Complete with an API Gateway

**Which service(s) is this request for?**
EKS-A

**Tell us about what you're submitting**
We are doing a Meetup talk on EKS-A showing how to install onto VMware. This is a deep dive into EKS-A including how to deploy an ingress gateway with Gloo Edge.

The Meetup is coming up on March 7 and will be held virtually. I hope that others in the community may attend!

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by chris-short** [comment]
Thoughts? @jicowan

I like the idea of including community gatherings related to EKS.

**Comment by rothgar** [comment]
I think an events section could be useful for people to learn more. Especially around Kubecon to give details about day-0 events.

**Comment by jicowan** [comment]
I'm in favor of putting a list of upcoming events in the newsletter, e.g. AWS webinars, CFTC, relevant community meetings, etc.

**Comment by murphye** [comment]
Great. Can you get this in Thursday's newsletter since the meetup is on the 7th?

Thank you,
Eric

**Comment by murphye** [comment]
@chris-short Are you able to get this in tomorrow's newsletter? Talk is on March 7.

**Comment by chris-short** [comment]
Yeah, it's in.
