### ISSUE TITLE
[Tips]: Can this newsletter be delivered as a 15-30min podcast?

### ISSUE THREAD

**Issue by djcoder100** [aws/eks-news#19]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**
URL: 
Title: 

**Which service(s) is this request for?**
All

**Tell us about what you're submitting**
What are some of the key points or benefits being suggested?
Listening to a podcast would be ideal for on the go and learning as you do other items.  With travel resuming it would be ideal to  get updates on the move.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by rothgar** [comment]
That's an interesting idea. I'm not sure if we have the time bandwidth to regularly record/edit/publish episodes and notes but if a portion of that could be automated with the existing content it could be a great alternative way for people to consume the content

**Comment by chris-short** [comment]
There would need to be two hosts I think. I could go for this.

**Comment by djcoder100** [comment]
Alternatively (if people are resources are an issue) - with a little rewrite to the newsletter you could Amazon Poily'fy this and have a speech translator do the work for you - perhaps? :-) 

Here is the latest news v007 with Polly to hear what it sounds like
[EKS News 007- Polly.mp3.zip](https://github.com/aws/eks-news/files/8156691/EKS.News.007-.Polly.mp3.zip)

**Comment by chris-short** [comment]
Thank you, @djcoder100. Let me see what I can do this week to get something spun up.

**Comment by chris-short** [comment]
This is still something that's going to happen. Working on some other issues before moving on to this.
