### ISSUE TITLE
[Tips]: vcluster now supports EKS Distro based virtual clusters

### ISSUE THREAD

**Issue by rothgar** [aws/eks-news#21]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**
URL: https://github.com/loft-sh/vcluster/releases/tag/v0.6.0
Title: vcluster now allows you to use EKS Distro binaries to create virtual clusters.

**Which service(s) is this request for?**
This could be EKS

**Tell us about what you're submitting**
What are some of the key points or benefits being suggested?
Users can use the same binaries with patches that EKS and EKS Anywhere uses fro their virtual clusters.

**Additional context**
Anything else we should know?
This isn't an officially supported distro of EKS but is an additional way to consume the official EKS binaries.
More partners and installation options can be found in the docs https://distro.eks.amazonaws.com/users/install/partners/

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by chris-short** [comment]
Included in EKS News 008: https://eks.news/archives/008/
