### ISSUE TITLE
[Tips]: March 9 Talk: Exposing your on-premises Amazon EKS-Anywhere cluster using Gloo Edge and Gloo Mesh

### ISSUE THREAD

**Issue by murphye** [aws/eks-news#22]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**
URL: https://hopin.com/events/solocon-2022/registration
Title: Exposing your on-premises Amazon EKS-Anywhere cluster using Gloo Edge and Gloo Mesh

**Which service(s) is this request for?**

EKS-A

**Tell us about what you're submitting**

Exposing on-premises workloads requires application networking changes, including provisioning new IP(s), load balancer(s), firewall(s), and Solo.io's API gateways and service mesh. During this talk, we'll help you get started quickly with EKS Anywhere by going through everything needed for you to quickly expose on-premises services using EKS Anywhere, AWS networking, and Gloo Edge and Gloo Mesh.

**Additional context**

SoloCon Event Talk, March 9 (Free to Register)

Jonah Jones, Solution Architect, AWS is presenting.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by murphye** [comment]
@chris-short Are you able to get this in tomorrow's newsletter? Jonah Jones is speaking. Thanks!!!

**Comment by chris-short** [comment]
Yep
