### ISSUE TITLE
RSS feed 404

### ISSUE THREAD

**Issue by sublimino** [aws/eks-news#23]
**Describe the bug**

https://eks.news/ has an RSS link to https://buttondown.email/eks.news/rss which returns a 404:

![image](https://user-images.githubusercontent.com/134117/156464175-d3f068a8-66d8-4489-b7d9-5606bf993aa6.png)

**Platform/OS/Hardware/Device**

Chrome 98

**To Reproduce (observed behavior)**

Browse to https://buttondown.email/eks.news/rss

**Expected behavior**

RSS feed previously at this address returns content, or replacement feed available 🙏 

**Additional context**

Link to archive from https://buttondown.email/eks.news also broken at https://eks.news/archive/eks-news-007/ which should be https://eks.news/archives/007/

**Comment by chris-short** [comment]
The RSS feed is at https://eks.news/index.xml
