### ISSUE TITLE
[Tips]: Building with Containers Twitter Space

### ISSUE THREAD

**Issue by chris-short** [aws/eks-news#43]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**
URL: https://twitter.com/i/spaces/1OwxWzAQEEVJQ
Title: Building with Containers

**Which service(s) is this request for?**
This could be Fargate, EKS, ECR, etc.
EKS

**Tell us about what you're submitting**
What are some of the key points or benefits being suggested?
How we build containers

**Additional context**
Anything else we should know?
@rothgar Anything you want to add?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by rothgar** [comment]
We talked about generic container tooling and AWS container services. Some of the benefits of using single container applications with App Runner and Lambda vs orchestration with ECS and EKS.

**Comment by chris-short** [comment]
Got it.
