### ISSUE TITLE
[Tips]: CFTC videos

### ISSUE THREAD

**Issue by rothgar** [aws/eks-news#45]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**
URL: https://www.youtube.com/watch?v=A-N_zwjJwL0
Title: Managing Kubernetes Helm charts with reckoner

URL: https://www.youtube.com/watch?v=Zk4If0h0cQ8
Title: EKS with Amazon GuardDuty

URL: https://www.youtube.com/watch?v=qbODDTkXMWw
Title: Kubernetes native testing with TestKube

URL: https://youtu.be/WmdauESk5JA
Title: Scaling containers in AWS with ECS, EKS, App Runner, Fargate, and Lambda

URL: https://www.youtube.com/watch?v=KNexvhb_DuY
Title: [Short] Kubernetes horizontal pod autoscaler (HPA)

**Which service(s) is this request for?**
EKS

**Tell us about what you're submitting**
What are some of the key points or benefits being suggested?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by rothgar** [comment]
Some of these might be duplicates from the last eks news episode. Here's the latest video https://www.youtube.com/watch?v=sXYNmnzbEFA

**Comment by chris-short** [comment]
Yeah, I've gotten those and the latest already. I'm pretty good about getting y'alls videos in. CFTC has its own section for a reason. Hopefully I'll be adding on to those in the future.
