### ISSUE TITLE
[Tips]: Zero to GitOps: Terraform and the AWS EKS Blueprints Project

### ISSUE THREAD

**Issue by tammersaleh** [aws/eks-news#54]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Please provide the URL and Title of the thing you'd like linked in the newsletter**
URL: https://superorbital.io/journal/terraform-aws-eks-blueprints/
Title: Zero to GitOps: Terraform and the AWS EKS Blueprints Project

**Which service(s) is this request for?**
EKS, AWS EKS Blueprints, KMS

**Tell us about what you're submitting**
This blog covers the new AWS EKS Blueprints, and shows how easy it is to get a really high quality gitops pipeline up and running using those tools.

**Comment by chris-short** [comment]
Going into EKS News 020
