### ISSUE TITLE
Issue 42 wasn't published

### ISSUE THREAD

**Issue by wjam** [aws/eks-news#85]
**Describe the bug**
Spotted that this repo was recently updated but didn't see a new article in my newsfeed. Looks like https://github.com/aws/eks-news/commit/73a343ce7db13e2882dd6e72600f820ed13d7a80 didn't pass CI?

**Comment by rothgar** [comment]
Thanks for the info. We'll look into it.

**Comment by jicowan** [comment]
Should be fixed now. It was a typo.
