### ISSUE TITLE
[Tips]: Could you add also an SNS topic where users could subscribe to?

### ISSUE THREAD

**Issue by daknhh** [aws/eks-news#98]
Last week AWS announced [Subscribe to AWS Daily Feature Updates via Amazon SNS ](https://aws.amazon.com/blogs/aws/subscribe-to-aws-daily-feature-updates-via-amazon-sns/)which is very nice also to integrate to Messengers like Slack etc. pp. - with better formatzing than Email. It would be nice if you also publish this eks-news trough a public SNS topic. 

Thanks best regards David

**Comment by jicowan** [comment]
We're planning to transition to a new platform relatively soon. We'll be able to do something like this at that time. Thanks for the suggestion @daknhh.
